### ISSUE TITLE
Emits null and undefined as literal strings which leads to ambiguous parsing on the server end

### ISSUE THREAD

**Issue by rjgotten** [canjs/can-param#19]
`can-param` emits both `null` and `undefined` values as literal strings, resulting in query strings where a server back end is no longer able to disambiguate them from the _actual_ string `"null"` or `"undefined"` values.

Would make more sense to special case these and _not_ emit properties for them.

https://github.com/canjs/can-param/blob/d0859c026c2a954bb4a4b2e0da7b967ed230661a/can-param.js#L16-L18

**Comment by eddypjr** [comment]
https://github.com/canjs/can-param/pull/20
