### ISSUE TITLE
Sort query params

### ISSUE THREAD

**Issue by Patrick-Ullrich** [canjs/can-param#21]
Sometimes query parameter order matters. e.g. when using the query string as a cache key. 

Proposed solution:
Sort the parameters before creating the query string.

**Comment by justinbmeyer** [comment]
We have a "sort" helper somewhere ...

```
param(sort(params))
```

**Comment by justinbmeyer** [comment]
https://canjs.com/doc/can-sort-object.html

https://github.com/canjs/can-sort-object

doesn't seem documented ...

**Comment by Patrick-Ullrich** [comment]
Will use `can-sort-object` in our project to get the sorted query string as pointed out above.
